url: http://www.beyondclick.com.br
name: BeyondClick
description: Este blog serve para manter um histórico sobre o que aprendi, estou avaliando, ou usando, no meu trabalho atual e freelances.
author: Antonio Carlos de Souza

encoding: UTF-8
include: ['_posts']
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']

markdown: rdiscount

relative_permalinks: false

analytics:
  google:
    tracking_id: UA-10335208-1

comments:
  disqus:
    short_name: acdesouza

search:
  engine:
    google: 005749088562750127864:-md_5pvlzuu
