title: BeyondClick
name: BeyondClick
email: acdesouza@beyondclick.com.br
description: >
  Este blog serve para manter um histórico sobre o que aprendi, estou avaliando ou usando, no meu trabalho atual e freelances.
url: http://www.beyondclick.com.br
github_username: acdesouza

# Build settings
encoding: UTF-8
include: ['_posts']
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']

markdown: kramdown

relative_permalinks: false # Default on GitHub Pages: https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
show_downloads: true

theme: jekyll-theme-minimal

google_analytics: UA-10335208-1

disqus:
  short_name: acdesouza

search:
  engine:
    google: 005749088562750127864:-md_5pvlzuu
